### ISSUE TITLE
Adding Feature Requests - milestone page is not editable

### ISSUE THREAD

**Issue by coranos** [CityOfZion/neo-mon#1]
I wanted to add a feature request, using the link on the mainpage:
https://github.com/CityOfZion/neo-mon/

Project: Milestone 1 -> https://github.com/CityOfZion/neo-mon/projects/1

But the milestone page is not editable. Please update instructions on how to add feature requests.

The feature I wanted to ask for is to add the code version to the monitor. (2.0.1.0 for example, the results of running the version command on the console, or sending a version command to port 10333)

**Comment by ffox77** [comment]
versions have been added to the dashboard
