### ISSUE TITLE
Interface improvement suggestions

### ISSUE THREAD

**Issue by rockacola** [CityOfZion/neo-mon#28]
Awesome work on the latest feature updates!

I have few suggestions that are close related, hence placing them in the same ticket:

1. Have prefix of 'ms' somewhere for latency. For the sake of clarity.
1. Rename 'offline' to 'unreachable', to avoid confusion that the node may be down (which is not proven to be the case)
1. When a node is detected to be 'unreachable', Have a 'last since' timestamp to indicates when this node was last detected per this web app instance.
1. With block height, please have a '-K', in red, indicates how many block it is behind from the highest chain. eg/ `#1,974,453 (-5)`.

**Comment by ffox77** [comment]
1. title of column is now  'Latency (ms)'
2. Renamed to unreachable
3. Last time connected is display for unreachable nodes that have been connected at least once after the client session started. Currently, one or two of the nodes have long latency and the requests can time out. You can see this 'time ago...' label show up for those intermittently.
4. Number behind best block is now shown
