### ISSUE TITLE
Support for https or redirection

### ISSUE THREAD

**Issue by Japh** [CityOfZion/neo-mon#3]
I visited https://monitor.cityofzion.io/ accidentally, and the site loads, but it shows all nodes as offline. Would be good if it still worked under https, or if not, that https automatically sent you to http or something.

**Comment by ffox77** [comment]
**https** is detected and redirected to **http**. the reason we don't run this location from https is not all RPC and Rest calls are https and a security exception would be thrown due to the mix.

**Comment by Japh** [comment]
Ah good, glad that was updated, thanks! :)
