### ISSUE TITLE
[idea] Add best RPC node endpoint

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-mon#62]
There's a good bunch of projects that use or used the `neon-wallet-db`, however it's being phased out and users are suggested to use the `neoscan` API instead. One of endpoint provided by `neon-wallet-db` was the `/best_node/` call, which in short gives you the address of the best responsive node to make  RPC calls to. Light wallets for example need this call unless they host a node themselves. `neoscan` provides a [get_all_nodes](https://neoscan.io/doc/Neoscan.Api.html#get_all_nodes/0) call but that only gives the P2P addresses + port, not the RPC ones. 

The `neo-mon` projects seems to have all the required information (and more) and would be a great candidate for a simple endpoint to provide either the most responsive node or the same data shown on  http://monitor.cityofzion.io/ but in JSON format. The service is there already, it would be great if we wouldn't force users to start web scraping the data.

Would love to hear your thoughts :)

**Comment by ffox77** [comment]
neo-mon is completely run on the client. There is no server side component as of yet hence no capability for a REST call. In the future, if there is enough demand and use, we may add server side to collect statistics over time and improve performance with sockets.
