### ISSUE TITLE
Column Sort

### ISSUE THREAD

**Issue by anfn101** [CityOfZion/neo-mon#63]
Would really like sorting within columns - country, endpoint, type, latency, version, is it up, block height, and peers, both decreasing and increasing. So for example, I could group by country code, or endpoint name. Can this be done? @ffox77

**Comment by ffox77** [comment]
It can be done. I'm looking into when will be a good time as I am currently working on upgrading to Angular 6.

**Comment by fabwa** [comment]
Update on this?
