### ISSUE TITLE
Expose an API endpoint that provides a JSON blob

### ISSUE THREAD

**Issue by phetter** [CityOfZion/neo-mon#87]
I'm working on some ideas that need a source of nodes alternative to neoscan get_all_nodes.
I understand I could cache a list, but I was wondering what robust solutions are available, if any.

I.e., I was hoping monitor.cityofzion.io exposed a list with the most recent ping times, version, etc. I suppose I can regenerate those pings and all easily enough, but why congest?

Thoughts?

**Comment by ffox77** [comment]
Neo-Mon doesn't have a server component. All monitoring is done from Client-side directly to registered Nodes and the registered nodes are defined in a static configuration file.

You might ask this question in Neo Discord to see if there is another solution that might have what you are looking for. There may be another project that has this, could be forked and adapted to your needs. If neo-scan has this, maybe you can start there.

**Comment by fabwa** [comment]
I guess this is closest to what you are looking for http://happynodes.f27.ventures/table

**Comment by phetter** [comment]
Yeah @fabwa, but is there an API? I looked and I don't see docs. It appears I'd have to read the code to learn the API; or scrape it which seems silly. JSON blob should be first features for something like this in todays dev world, yeah?
